### ISSUE TITLE
Not entirely clear where the dialogflow access token needs to go...

### ISSUE THREAD

**Issue by danleighton** [kkpoon/chat-web#1]
It seems to be in the index.html pasted in place of "your-dialogflow-access-token"... is that correct?

A few hints in the Readme would be brilliant :-)

Many thanks for taking the trouble to code this and put it out there! Much appreciated!

**Comment by kkpoon** [comment]
Thanks for the suggestion. I will update the README in next week. Thanks

**Comment by danleighton** [comment]
Awesome. Thanks very much.

**Comment by kkpoon** [comment]
hi @danleighton , the README has been updated. See if it does help. Thanks.

**Comment by danleighton** [comment]
Thanks @kkpoon. I did get it right in the end! Couldn't get the other stuff working...but that's another story ;-)

**Comment by kkpoon** [comment]
@danleighton Great.

Then I close this issue.
